version: '3.9'

services:
  postgres:
    container_name: book_postgres
    image: postgres:16
    volumes:
      - ~/pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB:${POSTGRES_DB}
      - POSTGRES_USER:${POSTGRES_USER}
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    env_file:
      .env

  django:
    container_name: book_django
    build:
      dockerfile: Dockerfile
      context: ./project
    depends_on:
      - postgres
    environment:
      - SECRET_KEY:${SECRET_KEY}
      - POSTGRES_ENGINE:${POSTGRES_ENGINE}
      - POSTGRES_DB:${POSTGRES_DB}
      - POSTGRES_USER:${POSTGRES_USER}
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
      - POSTGRES_HOST:${POSTGRES_HOST}
    volumes:
      - ./static_volume:/usr/src/app/staticfiles
      - ./media_volume:/usr/src/app/mediafiles
    env_file:
      .env
    command: >
      bash -c "python manage.py collectstatic --noinput && python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"

  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./nginx
    container_name: book_nginx
    image:  book_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static_volume:/static:rox
      - ./media_volume:/media:rox
    depends_on: 
      - django
    ports:
      - "80:80"



volumes:
  postgres_data:
  static:
  media:   
  nginx_conf: